# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf740433293fb7933217fbb2d089553ef935874c38b6698e269f128000515444375338d0a676315c193437faf10554e75f55bbb31e869441f46823b3ca46a4cd

test:
  secret_key_base: d6a8ca167cfd7b3437502097c3344ae43745e99d6b6684a243773a778914b249505cc3ab873c178e2f3fc7b3706c72a9ee2ab93c6f4434a07b48adb968c6801f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
